E-Commerce/Controllers/AuthController.cs
using E_Commerce.Model.Controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Commerce.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Index(string code)
        {
            ECommerce oECommerce = new ECommerce();
            if (!string.IsNullOrEmpty(code))
            {
                //Get Access Token
                string token = oECommerce.GetToken(code);

                var rrr = token.Split('-');

                Session["DataSession"] = oECommerce.GetUser(rrr[4], token);
                //Get Data User
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

E-Commerce/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_Commerce.Model.Controller;
using E_Commerce.Model;

namespace E_Commerce.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index(string id)
        {
            ECommerce oECommerce = new ECommerce();
            if (!string.IsNullOrEmpty(id))
            {
                var oQuery = oECommerce.GetCategory(id);

                if (oQuery.children_categories.Count == 0)
                {
                    return RedirectToAction("Search","Item",new { id =  id, type = "2" });
                }

                return View(oQuery);
            }
            Model.Models.ECommerce.Products.Category oResult = new Model.Models.ECommerce.Products.Category();
            oResult.children_categories = oECommerce.GetCategories(Model.Models.General.Enumerations.enumCountries.MCO.ToString());

            return View(oResult);
        }
    }
}

E-Commerce/Controllers/HomeController.cs
using E_Commerce.Model.Controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace E_Commerce.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            ECommerce oECommerce = new ECommerce();
            if (Session["DataSession"] != null)
            {
                return View(Session["DataSession"]);
            }
            return Redirect(oECommerce.GetUrlAuthorization());
        }


    }
}

E-Commerce/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Commerce.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

E-Commerce/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Commerce.Controllers
{
    public class ProfileController : Controller
    {
        // GET: Profile
        public ActionResult Index()
        {

            return View(Session["DataSession"]);
        }
    }
}

E-Commerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ECommerce</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:#a3bffb!important;">
        <strong><a class="navbar-brand" href="@Url.Action("Index", "Home")">E-Commerce</a></strong>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">

                
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Category")">Categorias</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @{ E_Commerce.Model.Models.ECommerce.User oUser = Session["DataSession"] != null ? (E_Commerce.Model.Models.ECommerce.User)Session["DataSession"] : new E_Commerce.Model.Models.ECommerce.User();}

                        @oUser.nickname 
                    </a>
                    <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="Url.Action("Index","Profile")">Ver Perfil</a>
                    </div>-->
                </li>

            </ul>

        </div>

    </nav>
    
   
    <div class="p-3 mb-2 bg-light text-dark" style="background-color: #a3bffb!important;">
        <div class="container">
            @using (Html.BeginForm("Search", "Item", FormMethod.Get, null))
            {
                <input class="form-control" type="text" name="id" value="" placeholder="Buscar Item" />
                <input type="hidden" name="type" value="1" />
            }
            
        </div>
    </div>


        <div class="container body-content">

            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Sebastian Martinez</p>
            </footer>
        </div>

        <script src="~/Scripts/jquery-3.2.1.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>